src/lib/grammar.rs
src/lib/mod.rs

Make the code a bit more Rusty. There shouldn't be any functional changes.

Code cleanups

---

src/lib/grammar.rs
src/lib/mod.rs
src/lib/pgen.rs
tests/test_pgen.rs

This branch is not finished yet. The next step would be to cache already calculated first sets within the first method.

Started work on first set computation

---

Cargo.toml
src/lib/pgen.rs
tests/test_pgen.rs

Add follow sets for parser generation

---

src/lib/mod.rs
src/lib/pgen.rs
src/main.rs
tests/test_pgen.rs
tests/test_yaccparser.rs

None of these were important, but they were starting to obscure real
problems...

Remove a number of warnings.

---

src/lib/grammar.rs
src/lib/mod.rs
tests/test_grammar.rs

It hadn't occurred to me use the unit type as its default return. Having done
that, this function is then a natural candidate for the try! macro.

Make the validator use the Result type.

---

src/lib/pgen.rs
tests/test_pgen.rs

This function takes a `Grammar` as input and then builds a `StateGraph` containing all states and their edges.
The `test_stategraph` uses the following grammar:
```
Z : S
S : Sb
bAa
A : aSc
a
aSb
```
the resulting graph looks like this (with one extra state `Start! : Z. {$}` and an additional rule `Start! : .Z {$}` in State #0):
Note that the state numbers may be different each execution due to the `LR1Items` being stored in a `HashSet` and thus being processed in arbitrary order.

Added function to build stategraphs

---

src/lib/pgen.rs
tests/test_pgen.rs

As well as the basic weakly compatible optimisation, this commit also maintains
a list of plausible candidate matches. It is thus about 15x faster on the Python
grammar.
As well as the obvious weakly compatible changes, this commit also doesn't store
itemsets' closures, only calculating them as needed. This makes the weakly
compatible checks faster and easier to understand. It does involve quite a few
changes to the tests that are probably worth thinking carefully about.

Implement much of Pager's weakly compatible optimisation.

---

src/lib/grammar.rs
src/lib/mod.rs
src/lib/stategraph.rs
src/lib/statetable.rs
src/main.rs

This implements a basic state graph -> state table conversion.

State table

---

src/lib/stategraph.rs

Doing the equivalent of pop() on a set is so slow, and the number of items so
small (for example, on the Java grammar, the median number of items in the todo
is 8), that we lose all the normal performance advantages of sets in this case.
On the Java grammar this speeds us up by about 10% overall.

Move close from a set todo to a vector.

---

src/lib/stategraph.rs

As things stand, this is a very minor optimisation (though it does make things
~2% faster). However, if we ever want to implement Pager's more sophisticated
change propagation, this is likely to prove useful.

Store closed_states along with core_states.

---

.travis.yml
Cargo.toml
src/lib/grammar.rs
src/lib/grammar_ast.rs
src/lib/statetable.rs
src/lib/yacc.rs

**Don't merge yet: comments only!**

Implement disambiguation rules.

---

src/lib/yacc.rs

Previously, the Yacc grammar parser incorrectly assumed that tokens in the header had to be literal names (e.g. `X`) when they can also be values (e.g. `'x'`).
With this, I can compile the PHP grammar (it takes about 1.1s on my machine).

Tokens in declarations don't have to be literals.

---

src/lib/stategraph.rs

Since the same state can be added to the todo list multiple times before it is
actually processed, we were previously creating closed sets that were never
actually used. This commit ensures that closed states are only created when
they're going to be used. On the PHP grammar, this speeds things up by about
10%.

Only calculate closed states when needed.

---

src/lib/stategraph.rs

This gives a roughly 15% speed-up on the PHP grammar.

Don't use a set for todos.

---

src/lib/yacc.rs

This is rather better than the previous "character offset" style of errors.
Before: "error at character offset 243". After: "error at line 6 col 5".

Report errors as line and column numbers.

---

src/lib/yacc.rs

As soon as one uses multi-byte unicode symbols (e.g. ❤, which takes two bytes),
then one notices that these &""[x..y] is doing something different than
&"".chars().take(x). The former works on bytes, the latter on codepoints (what
we would typically call characters). I had naively assumed that both operate on
codepoints.
This patch fixes this by being clear that the indexes it is passing around are
always bytes. So if one wants to access a char at byte 'i' one has to do
&s[i..].chars().next(). This feels a bit clumsy, but is much faster than the
(incorrect!) &s.chars().skip(i).next() which has to do a linear scan over the
whole string to find the ith character; in other words, the cost of obtaining
this is O(n), not O(1) as expected.
Because of that, this patch has the pleasant …

Deal with Rust Strings bytes / codepoints conflation.

---

src/lib/yacc.rs

It turned out to be easier to do a slightly deeper fix, and store a '0'th
newline, and also make the newlines list be the character *after* each newline.
[Yes, this PR has too many hearts in it. Oh well.]

Fix error reporting in the face of multibyte characters.

---

src/lib/stategraph.rs

It's not clear that one needs this with Pager's algorithm, but without it, one
can't turn the weakly compatible check off (since the program endlessly creates
more and more states). When we do find an exactly equivalent state, we also have
the advantage that we don't need to do any change propagation, so it's probably
a small optimisation as well. [FWIW, this is clearly what Hyacc does; Chen makes
a vague mention to "the same" states in his thesis, which is where I got the
idea from.]

Before state merging, try finding an exactly equivalent state.

---

src/lib/mod.rs
src/lib/statetable.rs

I thought that we *might* be able to catch this earlier than table generation by detecting "pointless" cycles / loops. However, I think (but need to confirm) that there are some valid LR grammars which can use this idiom (albeit pointlessly). So I need to think a bit more about that before doing something; this commit, at least, gives the user some chance of debugging their problem.
Addresses #63.

Report accept/reduce conflicts via a Result rather than a panic.

---

src/lib/ast.rs
src/lib/firsts.rs
src/lib/grammar.rs
src/lib/itemset.rs
src/lib/pager.rs
src/lib/stategraph.rs
src/lib/statetable.rs
src/lib/yacc_parser.rs

This PR brings lrtable up to more modern Rust standards: each commit is self-contained and (hopefully) self-describing.

Modernise the code a touch

---

src/lib/firsts.rs
src/lib/itemset.rs
src/lib/mod.rs
src/lib/pager.rs
src/lib/statetable.rs

This PR reflects the move of some code to lrtable, and the consequent API changes.

Reflect changes in cfgrammar.

---

.travis.yml
src/lib/mod.rs
src/lib/pager.rs
src/lib/stategraph.rs
src/lib/statetable.rs

This is a series of not-very-related commits that are needed for lrpar (except for the pretty printer -- which isn't *needed* but was useful). In essence each commit either exposes more information from lrtable or changes the API to make it a bit more future proof. Hopefully, the commit messages for each should make clear what they're doing.

Changes for lrpar

---

src/lib/stategraph.rs

Brings lrtable up to date with rust nightly API.

Box iterators.

---

src/lib/firsts.rs
src/lib/itemset.rs
src/lib/pager.rs
src/lib/stategraph.rs
src/lib/statetable.rs

See https://github.com/softdevteam/cfgrammar/pull/18 for justification.
[I'll need to kick the tests.]

The great unwrapping

---

src/lib/statetable.rs

Since a state table can only have a single accept entry, exposing this to the user is safe. This is needed for some work in lrpar.

Expose to the user which state is the final state.

---

src/lib/statetable.rs

This PR is two vaguely-related changes: https://github.com/softdevteam/lrtable/commit/0f9416664bb9c77fd80db4b95391224ee3f496ab is a performance fix; https://github.com/softdevteam/lrtable/commit/350cfb193937bce86ee27285b5fe57e11fcb133f is an API change. The second commit leads to lots of not-very-interesting mechanical churn, so it's best to look at the commits separately.

State table changes

---

src/lib/statetable.rs

I should have done this in the previous PR. Mea culpa!

The state_actions iterator should reflect state_action and return a TIdx.
