softdevteam/lrtable

.travis.yml
This currently targets the Rust nightly build, as lrpar needs some of its
functionality. Once Rust moves to 1.2beta, we should change to using beta and
after that, assuming Travis supports it, to stable.
=> Add initial Travis config file.

src/main.rs
This also fixes the "unused variables" warning.
=> If a message is passed to usage, do something with this.

src/lib/mod.rs, tests/test_yaccparser.rs
I fear these actually show that the current parsing scheme doesn't quite work. For example, I think the intention is that empty inputs should succeed but the code doesn't allow them. Nevertheless, this pull request fixes some obvious crashes in a minimal way.
=> Catch some crashes when partly or wholly empty inputs are used.

src/lib/grammar.rs, tests/test_grammar.rs
Other parts of the code such as the FIRSTS calculation assume that all tokens
and rule references resolve. This function guarantees that this assumption is
valid.
=> Add a simple validator.

src/lib/mod.rs, src/main.rs, tests/test_pgen.rs, tests/test_yaccparser.rs
The vague aim here is that one can have multiple input formats which reuse
most kinds of errors.
=> Unify the error interface to Yacc parsing.

src/lib/grammar.rs, src/lib/pgen.rs, src/lib/yacc.rs, tests/test_yaccparser.rs
This makes various bits of code a little easier (and will make the future "move
to ints" refactoring much easier) and shorter.
=> Refactor Symbol to be a single enum rather than a struct and an enum.

src/lib/grammar.rs, src/lib/yacc.rs, tests/test_grammar.rs, tests/test_yaccparser.rs
It's not entirely clear to me if this is exactly what Yacc does, but the
previous rules were definitely too restrictive. This makes porting examples
from other sources quite a bit easier.
=> Be more flexible about what nonterminal and terminal names can be.

src/lib/pgen.rs
Before we allocated memory as soon as we found an active item, which was
(mostly) completely pointless. This unnecessarily slowed down things.
=> Only allocate memory if goto actually finds a matching symbol.

src/lib/pgen.rs, tests/test_pgen.rs
Instead of representing all the lookaheads of a set of items as a single
contiguous item, this breaks them up into one bitvec per item. This makes
reasoning about the data-structure a little easier, and also allows us to make
use of BitVec::union in some performance critical corners. It also requires less
memory to be allocated, as dots that aren't active require a single None (rather
than grm.terms_len bits).
On the Python grammar on my machine, this patch uses about 40% less memory and
is a bit over 2x faster.
=> Change the representation of items away from a single bitvec.

src/lib/grammar.rs, src/lib/pgen.rs, tests/test_grammar.rs
This means that all later processing is deterministic, which should make
debugging (and performance analysis!) predictable, as well as ensure that we
don't have nondeterministic test failure (which I had seen previously, albeit
only when I'd made other mistakes).
This also fixes a very subtle bug, where what was called start_rule was
incorrect: it should have been storing the start alternative. Things happened to
work because previously the start rule and start alternative both happened to be
0.
=> Store nonterminals in (case insensitive) alphabetical order.

src/lib/mod.rs, src/lib/pgen.rs, tests/test_pgen.rs
In essence, this commit implements a more traditional, mildly optimised
Knuth-ish LR state generator. Itemsets are now HashSets with keys (alternative
offset, dot) mapping to contexts (i.e. lookaheads). This allows us to simplify
the implementation somewhat which is particularly noticeable in the goto()
function.
However, more significantly we are able to get rid of the significant number of
RefCells of the previous version. These appeared necessary because we are often
iterating over a data-structure and modifying it at the same time. However,
because of the quantity of RefCells we were using, we were spending huge amounts
of time in reading/writing the borrowing state. This commit makes use of todo
lists, splitting up iterating over a data-structure (and adding things to a todo
list) …
=> Simplify the representation used by moving to sets of items.

src/lib/grammar_ast.rs
This is a relatively trivial pull request, but it helped me debug a Pascal grammar, so it is useful.
=> Marginally improve error messages when validating grammars.

src/lib/grammar.rs, src/lib/grammar_ast.rs, src/lib/stategraph.rs, src/lib/statetable.rs, src/lib/yacc.rs
"Rule" is (mostly) used where "nonterminal" was.
"Production" is (mostly) used where "alternative" previously used.
A few types have been renamed accordingly.
The aim is to bring us into line with the general literature so that people
aren't forced to waste time working out what terminology we're using.
There should be no functional change whatsoever.
=> Use standard terminology and expand a few definitions.

Cargo.toml, src/lib/mod.rs, src/lib/yacc.rs
This was previously particularly punishing on large grammars. With this commit, the PHP grammar takes under 0.5s to fully process, and is over 200x faster than Eco. So I think we're now fast enough.
=> Cache regexes rather than building them anew on every use.

src/lib/stategraph.rs
In a typical description of this algorithm -- and in the previous implementation
-- one has a todo set which contains pairs (prod_i, dot). Unfortunately this is
a slow way of doing things. Searching the set for the next item and removing it
is slow; and, since we don't know how many potential dots there are production,
the set is of potentially unbounded size, so we can end up resizing memory.
Since this function is the most expensive in the table generation, using a
HashSet (which is the "obvious" solution) is pretty slow.
However, we can reduce these costs through two observations:
1) The initial todo set is populated with (prod_i, dot) pairs that all come
from self.items.keys(). There's no point copying these into a todo list.
2) All subsequent todo items are of the form (prod_off, 0). …
=> Speed up set closure by using a fixed amount of memory.

src/lib/yacc.rs
This fixes two bugs in reporting where errors occur in an LR grammar. The first commit avoids this happening:
```
thread 'yacc::test::test_programs_not_supported' panicked at 'attempt to subtract with overflow', src/lib/yacc.rs:85
failures:
yacc::test::test_programs_not_supported
```
=> Fix line reports

src/lib/grammar.rs, src/lib/mod.rs
Chiefly a simple way of getting a rule index from a production index.
=> Expose some internals needed by lrpar.

src/lib/grammar.rs, src/lib/mod.rs, src/lib/stategraph.rs, src/lib/statetable.rs
Previously, the API that lrtable exposed had lots of public attributes, which gave people quite a bit of opportunity to unintentionally rely on details that we may wish to change in the future.
This PR is arguably a series of PRs; it's lots of commits that incrementally move us towards an API that exposes many fewer public things. The end result looks huge, so it's probably better to review one commit at a time (in reverse chronological order). There are two major types of commits: introduce a newtype for X (i.e. a newtype for usize which means that rustc won't automatically cast between X and usize); or make X private. In both cases, the "main" change is simple; dealing with the fallout in the tests then requires lots of (mostly manual) fiddling. So much of the bulk of the change is …
=> Lockdown, and make more consistent, the external API.

src/lib/statetable.rs
This is part of an otherwise-aborted branch where I tried moving the statetable from a hashmap to a list (it made no measurable difference, so I'll stick with the current solution which is more memory efficient). However, these two commits arguably make things a little easier to understand, so are worth merging anyway,
=> Hashmap to list

src/lib/ast.rs, src/lib/grammar.rs, src/lib/yacc_parser.rs
This allows Yacc grammars like the following to be accepted and, hopefully, work correctly:
```
%start expr
%left '+' '-'
%left '*' '/'
%%
expr : expr '+' expr
| expr '-' expr
| expr '*' expr
| expr '/' expr
| %prec '-'  expr '*'
| 'id' ;
```
=> Add support for %prec

src/lib/grammar.rs, src/lib/yacc_parser.rs
I don't know why I ever used the long-winded version in the first place.
=> Replace x.get(y).unwrap() with x[y].

src/lib/stategraph.rs
First, it wasn't actually executing as a doc test. Second, it had an incorrect assertion:
```
assert!(firsts.is_epsilon_set(grm.nonterminal_off("S")));
```
However, since Firsts is private to stategraph.rs, testing it as a doc test is impossible (there's no way to "use" Firsts). So there's no point pretending this comment is anything other than a bog-standard comment. So turn the doc test into a comment and fix the assertion.
=> This docstring was broken.

src/lib/firsts.rs, src/lib/itemset.rs, src/lib/pager.rs, src/lib/stategraph.rs, src/lib/statetable.rs
Follows on from https://github.com/softdevteam/cfgrammar/pull/7. In lrtable we use the fact that we can store an EOF bit in contexts at `grm.terms_len()` (as discussed in the other PR).
[Also deals with the other minor changes squeezed into the last cfgrammar PR. Best to look at the commits individually.]
=> Remove explicit EOF term

Cargo.toml
Most usefully, lrtable no longer needs regex at all (that functionality is now
entirely within cfgrammar), so we can remove that dependency entirely.
=> Update library dependencies.

src/lib/firsts.rs, src/lib/itemset.rs, src/lib/pager.rs, src/lib/stategraph.rs, src/lib/statetable.rs
The minimal changes implied by https://github.com/softdevteam/cfgrammar/pull/9
=> Reflect that the explicit EOF term is back in cfgrammar.

src/lib/firsts.rs, src/lib/itemset.rs, src/lib/pager.rs, src/lib/stategraph.rs, src/lib/statetable.rs
[non]term_off is now [non]term_idx (and now returns `Option`). This is a mechanical change (I used `srep` for it).
[I should have made this PR a few days ago, but somehow forgot!]
=> Reflect changes in cfgrammar.

src/lib/itemset.rs, src/lib/mod.rs, src/lib/statetable.rs
Previously we represented actions as a mapping from a tuple (state index1, non-terminal index) -> state index2. In other words, if you were in "state index1" and encountered a non-terminal, you could look up which state you should move to next.
This works well enough for normal parsing, but not for error recovery, where one often needs to know "which non-terminals are valid actions for state S?" This PR cheats a little, changing the mapping to state table offset -> state index. We use the normal statetable representation where rows represent states and columns represent terminals. Thus the statetable:
```
A         B
0  shift 1
1  shift 0  reduce B
```
is represented as a hashtable `{0: shift 1, 2: shift 0, 3: reduce 4}`. This allows us to do a faster (although still not far from optimal) …
=> Sparse table for actions

Cargo.toml, src/lib/firsts.rs, src/lib/itemset.rs, src/lib/mod.rs, src/lib/pager.rs
This PR minimally and mechanically moves lrtable from using `BitVec` to `Vob`. This gives roughly a 10% speedup on building the Java grammar (which includes lots of bits which don't do any bitvector stuff at all). That said, don't expect this to be hugely noticeable: the overall time to build the whole grammar is around 0.1s. Every little helps though.
As explained in https://docs.rs/vob/0.1.0/vob/struct.Vob.html, porting from `BitVec` to `Vob` is almost entirely mechanical *except* calls to `clear` in `BitVec` need to be ported to `set_all(false)` in `Vob`.
=> Move to Vob

src/lib/firsts.rs, src/lib/itemset.rs, src/lib/mod.rs, src/lib/pager.rs, src/lib/stategraph.rs, src/lib/statetable.rs
This PR moves lrtable to using `u32` instead of `usize`. It does this in three chunks to make reviewing a bit easier, though all three commits are semi-mechanical. [Note the middle commit doesn't replicate `cfgrammar`s macro, because we only have one u32-api-but-stores-u16-struct.]
=> Newtype changes

src/lib/firsts.rs, src/lib/statetable.rs
This small PR starts with two minor optimisations (slightly reducing memory usage) before introducing a more significant one (switching to using the FNV hasher, which is much more effective on small integers). It ends up with an unrelated doc test fix, which seems to have been tickled by an update in Rust.
=> Optimisations

src/lib/statetable.rs
[Needs https://github.com/softdevteam/cfgrammar/pull/23 to be merged first. Once that's merged, the tests in here will need kicking to ensure that the Cerecke test succeeds.]
This reflects the recent changes to cfgrammar. It means that we now deal correctly with less common examples such as that derived from Cerecke's PhD thesis.
=> Reflect cfgrammar out of order change

Cargo.toml, src/lib/itemset.rs, src/lib/stategraph.rs, src/lib/statetable.rs
NB: https://github.com/softdevteam/lrtable/pull/87 needs to be merged first. I might need to toggle the "base" above back to "master" and maybe do a rebase.
lrpar's error recovery functions spend a long time querying the statetable: that means lots of hash table lookups which, cumulatively, become very costly. This commit enables the recoverers to reduce the number of lookups.
There are a few related things in here:
1) Use the new Range facility in Vob's iter_set_bits to speed up the existing
state_actions function.
2) Add a new helper function state_shifts which tells users only which entries
are shifts (i.e. it won't tell you where reduces or accepts are). If you
only care about searching for shifts, this saves a lot of hashtable
lookups.
3) Add a more esoteric helper function …
=> Add helper functions to make error recovery faster.

.travis.yml, src/lib/statetable.rs
This allows us to test if a state 1) only contains reduce actions 2) each reduce action reduces to the same production.
We'll be using this in lrpar shortly (probably).
=> Add "reduce_only_state".
